---
- name: Manage moosenet Raspberry Pi 3
  hosts: raspi
  remote_user: madmin
  gather_facts: true

  vars:
    ipa_auto_enroll: yes

  roles:
    - common

  tasks:
    - name: puppet package
      package:
        name: puppet
        state: installed

    - name: puppet service
      service:
        name: puppet
        enabled: yes
        state: running

