- name: IPA get-cert
  hosts: all
  become: yes
  vars:
    ipa_getcert_app: 'foreman'
    ipa_getcert_ssl_key: "/etc/pki/tls/private/{{ ipa_getcert_app }}_{{ inventory_hostname }}.key"
    ipa_getcert_ssl_cert: "/etc/pki/tls/certs/{{ ipa_getcert_app }}_{{ inventory_hostname }}.cert"
    ipa_getcert_ssl_ca: "/etc/pki/tls/certs/{{ ipa_getcert_app }}_{{ inventory_hostname }}.ca"

    ipa_getcert_cmd: /usr/bin/ipa-getcert

  tasks:
    - name: register cert
      command: >
        "{{ ipa_getcert_cmd }} request -N {{ ipa_getcert_app }} -r -k {{ ipa_getcert_ssl_key }} -f {{ ipa_getcert_ssl_cert }} -F {{ ipa_getcert_ssl_ca }}"
