---
- name: moose site file
  hosts: all

  vars:

  vars_files:

  roles:

  tasks:

- name: deploy setup
  hosts: config
  vars_files:
    - vars/deploy.yml
  tasks:
    - name: deploy tasks
      include_tasks:
        name: tasks/deploy.yml

- name: provision setup
  hosts: provision
  vars_files:
    - vars/provision.yml
  tasks:
    - name: provision tasks
      include_tasks: 
        name: tasks/provision.yml
