---
- name: moose site file
  hosts: all

  vars:

  vars_files:

  roles:

  tasks:

- name: deploy setup
  hosts: config

- name: provision setup
  hosts: provision

  vars_files:
    - vars/foreman.yml

  tasks:
    - name: foreman tasks
      include_tasks: 
        name: tasks/foreman.yml
