---
- name: Push Public SSH Key
  hosts: all
  gather_facts: false
  vars:
    ssh_public_key: https://github.com/thechuckmo.keys
  roles:
    - common
  tasks:
    - name:
      authorized_key:
        #user: "{{ lookup('env', 'USER') }}"
        user: "{{ ansible_user }}"
        state: present
        manage_dir: "yes"
        key: "{{ ssh_public_key }}"
        exclusive: "yes"
