# foreman build and configuration using Forklift
# https://github.com/theforeman/forklift
---
- name: Foreman configuration
  hosts: provision
  become: yes
  vars:
    ipa_getcert_name: 'foreman'

    katello_repositories_version: 3.6
    foreman_repositories_version: 1.17
    foreman_installer_options:
      - "--foreman-admin-first-name Admin"
      - "--foreman-admin-last-name Foreman"
      - "--foreman-organizations-enabled true"
      - "--foreman-initial-organization moosejudge"
      - "--foreman-locations-enabled true"
      - "--foreman-initial-location home"
      - "--enable-foreman-plugin-cockpit"
      - "--enable-foreman-plugin-templates"
      - "--enable-foreman-plugin-expire-hosts"
      - "--enable-foreman-plugin-remote-execution"
    foreman_installer_authentication:
      - "--foreman-ipa-authentication true"
      - "--foreman-proxy-realm true"
      - "--foreman-proxy-realm-principal 'realm-proxy@HOME.MOOSEJUDGE.COM'"
    foreman_installer_provision:
      - "--foreman-proxy-dhcp true"
      - "--foreman-proxy-dhcp-managed true"
      - "--foreman-proxy-dhcp-provider isc"
      - "--foreman-proxy-dhcp-range '10.10.10.100 10.10.10.200'"
      - "--foreman-proxy-dhcp-interface eth1"
      - "--foreman-proxy-dhcp-subnets '10.10.10.0/24'"
      - "--enable-foreman-compute-libvirt" 
      - "--enable-foreman-compute-gce"
      - "--foreman-proxy-libvirt-network provision"
      - "--foreman-proxy-libvirt-connection 'qemu+ssh://vmadmin@hv1.home.moosejudge.com'"
    foreman_installer_config:
      - "--enable-foreman-plugin-ansible"
      - "--puppet-server-git-repo true"
      - "--puppet-autosign-entries '*.home.moosejudge.com'"

        #- "--foreman-ssl-cert {{ ssl_foreman_crt }}"
        #- "--foreman-ssl-key {{ ssl_foreman_key }}"
        #- "--foreman-ssl-ca {{ ssl_foreman_ca }}"
  roles:
    - role: ipa-getcert 
      tags: [repos]
      #- role: foreman
      #tags: [install]
  tasks:
    - name: foreman-installer install 
      include_role: 
        name: foreman
      tags: [foreman, install, base]

    - name: foreman-installer config
      include_role:
        name: foreman_installer
      vars:
        foreman_installer_options: "{{ foreman_installer_config }}"
      tags: [foreman, install, config]

    - name: foreman-installer authentication
      include_role:
        name: foreman_installer
      vars:
        foreman_installer_options: "{{ foreman_installer_authentication }}"
      tags: [foreman, install, authentication]

    - name: foreman-installer provision
      include_role:
        name: foreman_installer
      vars:
        foreman_installer_options: "{{ foreman_installer_provision }}"
      tags: [foreman, install, provision]

    - name: firewall Satellite service
      firewalld:
        immediate: yes
        permanent: yes
        service: RH-Satellite-6
        state: enabled
      tags: [firewall]

    - name: foreman ssh-key prep
      file:
        name: /usr/share/foreman/.ssh
        state: directory
        owner: foreman
        group: foreman
        mode: 0700
      tags: [ssh-key, provision]

    - name: foreman ssh-key create
      user:
        name: foreman
        generate_ssh_key: yes
        ssh_key_file: /usr/share/foreman/.ssh/id_rsa
        ssh_key_bits: 2048
        ssh_key_type: rsa
      tags: [ssh-key, provision]

    - name: get foreman public key
      slurp:
        src: /usr/share/foreman/.ssh/id_rsa.pub
      register: libvirt_sshkey
      tags: [ssh-key, provision]

    - debug: 
        msg: "ssh key: {{ libvirt_sshkey.content | b64decode }}"

    - name: adding libvirt ssh-key
      authorized_key:
        user: vmadmin
        key: "{{ libvirt_sshkey.content | b64decode }}"
      delegate_to: hv1.home.moosejudge.com
      tags: [ssh-key, provision]
        
