---
- name: NTP Clients
  hosts: all
  become: yes
  vars:
    ntp_timezone: America/Los_Angeles
    ntp_enabled: yes
    ntp_manage_config: yes

    ex_ntp_area: north-america
    in_ntp_servers:
      - core.home.moosejudge.com
  tasks:
    - name: ntp client config
      include_role: 
        name: ntp
      vars:
        ntp_servers: "{{ in_ntp_servers }}"
      when: not ntp_server

    - name: ntp server config
      include_role:
        name: ntp
      vars:
        ntp_area: "{{ ex_ntp_area }}"
      when: ntp_server
