- name: ipa-getcert
  include_role:
    name: ipa-getcert
  tags: [ipa, getcert]

- name: foreman-installer install 
  include_role: 
    name: foreman
  tags: [foreman, install, base]

- name: foreman-installer config
  include_role:
    name: foreman_installer
  vars:
    foreman_installer_options: "{{ foreman_installer_config }}"
  tags: [foreman, config]

- name: foreman-installer authentication
  include_role:
    name: foreman_installer
  vars:
    foreman_installer_options: "{{ foreman_installer_authentication }}"
  tags: [foreman, authentication]

- name: foreman-installer network
  include_role:
    name: foreman_installer
  vars:
    foreman_installer_options: "{{ foreman_installer_network }}"
  tags: [foreman, network]

- name: foreman-installer compute
  include_role:
    name: foreman_installer
  vars:
    foreman_installer_options: "{{ foreman_installer_compute }}"
  tags: [foreman, compute]

- name: firewalld Satellite
  block:
    - name: firewalld services
      firewalld:
        immediate: yes
        permanent: yes
        state: enabled
        service: "{{ item }}"
      with_items: "{{ foreman_firewall_services }}"
    - name: firewalld ports
      firewalld:
        immediate: yes
        permanent: yes
        state: enabled
        port: "{{ item }}"
      with_items: "{{ foreman_firewall_ports }}"
  tags: [firewall]

- name: foreman ssh-key prep
  file:
    name: /usr/share/foreman/.ssh
    state: directory
    owner: foreman
    group: foreman
    mode: 0700
  tags: [ssh-key]

- name: foreman ssh-key create
  user:
    name: foreman
    generate_ssh_key: yes
    ssh_key_file: /usr/share/foreman/.ssh/id_rsa
    ssh_key_bits: 2048
    ssh_key_type: rsa
  tags: [ssh-key]

- name: get foreman public key
  slurp:
    src: /usr/share/foreman/.ssh/id_rsa.pub
  register: libvirt_sshkey
  tags: [ssh-key]

- name: adding libvirt ssh-key
  authorized_key:
    user: vmadmin
    key: "{{ libvirt_sshkey.content | b64decode }}"
  delegate_to: hv1.home.moosejudge.com
  tags: [ssh-key]
   
- name: ansible packages
  package:
    name: [ansible, ansible-doc, ansible-review]
    state: installed
  tags: [ansible]
