- name: ipa-getcert
  include_role:
    name: ipa-getcert
  tags: [ipa, getcert]

- name: foreman-installer install 
  include_role: 
    name: foreman
  tags: [foreman, install, base]

- name: foreman-installer config
  include_role:
    name: foreman_installer
  vars:
    foreman_installer_options: "{{ foreman_installer_config }}"
  tags: [foreman, install, config]

- name: foreman-installer authentication
  include_role:
    name: foreman_installer
  vars:
    foreman_installer_options: "{{ foreman_installer_authentication }}"
  tags: [foreman, install, authentication]

- name: foreman-installer provision
  include_role:
    name: foreman_installer
  vars:
    foreman_installer_options: "{{ foreman_installer_provision }}"
  tags: [foreman, install, provision]

- name: firewall Satellite service
  firewalld:
    immediate: yes
    permanent: yes
    service: RH-Satellite-6
    state: enabled
  tags: [firewall]

- name: foreman ssh-key prep
  file:
    name: /usr/share/foreman/.ssh
    state: directory
    owner: foreman
    group: foreman
    mode: 0700
  tags: [ssh-key, provision]

- name: foreman ssh-key create
  user:
    name: foreman
    generate_ssh_key: yes
    ssh_key_file: /usr/share/foreman/.ssh/id_rsa
    ssh_key_bits: 2048
    ssh_key_type: rsa
  tags: [ssh-key, provision]

- name: get foreman public key
  slurp:
    src: /usr/share/foreman/.ssh/id_rsa.pub
  register: libvirt_sshkey
  tags: [ssh-key, provision]

- debug: 
    msg: "ssh key: {{ libvirt_sshkey.content | b64decode }}"

- name: adding libvirt ssh-key
  authorized_key:
    user: vmadmin
    key: "{{ libvirt_sshkey.content | b64decode }}"
  delegate_to: hv1.home.moosejudge.com
  tags: [ssh-key, provision]
    
