# foreman build and configuration using Forklift
# https://github.com/theforeman/forklift
---
- name: Foreman configuration
  hosts: foreman
  gather_facts: yes
  remote_user: madmin@home.moosejudge.com
  become: yes
  vars:

  roles:
    - role: epel_repositories
    - role: ostree_repositories
    - role: puppet_repositories
    - role: foreman_repositories
    - role: katello_repositories
    - role: foreman_installer
      scenario: katello
      foreman_installer_additional_packages:
        - katello
      foreman_installer_options_internal_use_only:
        - "--disable-system-checks"
        - "--enable-foreman-plugin-discovery"
        - "--enable-foreman-plugin-bootdisk"
        - "--enable-foreman-plugin-remote-execution"
        - "--enable-foreman-plugin-hooks"
        - "--enable-foreman-plugin-openscap"
        - "--enable-foreman-proxy-plugin-openscap"
        - "--enable-foreman-proxy-plugin-remote-execution-ssh"
