---
# ipa_getcert settings
ipa_getcert_cmd: '/usr/bin/ipa-getcert'
ipa_getcert_never_unregister: no

# default locations
ipa_getcert_ssl_dir: '/etc/pki/tls'
ipa_getcert_ssl_certs_dir: "{{ ipa_getcert_ssl_dir }}/certs"
ipa_getcert_ssl_private_dir: "{{ ipa_getcert_ssl_dir }}/private"

# default single certificate action
ipa_getcert_name: 'https'
ipa_getcert_state: register
ipa_getcert_renew: yes

# these will be register after run
# ipa_getcert_ssl_key: "{{ ipa_getcert_ssl_private_dir }}/{{ ipa_getcert_name }}_{{ inventory_hostname }}_key.pem"
# ipa_getcert_ssl_ca: "{{ ipa_getcert_ssl_certs_dir }}/{{ ipa_getcert_name }}_{{ inventory_hostname }}_ca.pem"
# ipa_getcert_ssl_cert: "{{ ipa_getcert_ssl_certs_dir }}/{{ ipa_getcert_name }}_{{ inventory_hostname }}_cert.pem"

# list for managing multipile ipa certificates
ipa_getcert_ssl_certs:
  - { name: "{{ ipa_getcert_name }}", state: "{{ ipa_getcert_state }}", renew: "{{ ipa_getcert_renew }}" }
