---
ansible_cfg: cfg/prod/ansible.cfg

redis_setup: yes
redis_pkgs: [redis, python-redis]

prov_user: madmin
prov_group: madmin

prov_base: '/opt/config'
prov_roles: "{{ prov_base }}/roles"

prov_forklift_repo: "https://github.com/theforeman/forklift.git"
prov_forklift: "{{ prov_base }}/forklift"

